from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
SLOTS_ROOT = DOCS / "assets" / "images" / "slots"
OUTPUT = DOCS / "_generated" / "image_slots.md"
VALID_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".svg"}


def slot_dirs() -> list[Path]:
    if not SLOTS_ROOT.exists():
        return []
    return sorted(path for path in SLOTS_ROOT.iterdir() if path.is_dir())


def slot_images(slot_dir: Path) -> list[Path]:
    images = [
        path
        for path in slot_dir.iterdir()
        if path.is_file()
        and path.suffix.lower() in VALID_EXTENSIONS
        and path.name.lower() != "readme.md"
    ]
    return sorted(images, key=lambda path: path.name.lower())


def choose_image(images: list[Path]) -> Path | None:
    if not images:
        return None

    custom = [path for path in images if not path.stem.lower().startswith("placeholder")]
    if custom:
        return custom[0]
    return images[0]


def relpath(path: Path) -> str:
    return path.relative_to(DOCS).as_posix()


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "[slot-hero]: assets/images/slots/hero/placeholder.svg",
        "[slot-repository-side]: assets/images/slots/repository-side/placeholder.svg",
        "[slot-website-side]: assets/images/slots/website-side/placeholder.svg",
    ]

    warnings: list[str] = []

    for slot_dir in slot_dirs():
        images = slot_images(slot_dir)
        selected = choose_image(images)
        if selected is None:
            continue

        slot_name = slot_dir.name
        ref_name = f"[slot-{slot_name}]"
        ref_value = relpath(selected)
        entry = f"{ref_name}: {ref_value}"

        existing = next((index for index, line in enumerate(lines) if line.startswith(f"{ref_name}:")), None)
        if existing is None:
            lines.append(entry)
        else:
            lines[existing] = entry

        if len(images) > 1:
            warnings.append(
                f"Slot '{slot_name}' has {len(images)} image files; using '{selected.name}'."
            )

    content = [
        "<!-- This file is generated by scripts/generate_image_slots.py. -->",
        "",
        *lines,
        "",
    ]

    OUTPUT.write_text("\n".join(content), encoding="utf-8")

    print(f"Generated {OUTPUT.relative_to(ROOT)} with {len(lines)} slot reference(s).")
    for warning in warnings:
        print(f"Warning: {warning}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
