name: build-and-push-jupyterlab-image

on:
  workflow_dispatch:  # This allows you to manually trigger the action from GitHub UI.

jobs:
  
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
            
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get lowercase repo name (for dynamic tags)
        id: repo_name
        run: |
          lowercase_name=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')
          echo "repo_name=${lowercase_name}" >> "$GITHUB_OUTPUT"
        
      - name: Build and push latest
        id: docker_build_jupyterlab
        uses: docker/build-push-action@v5
        with:
          context: containers/jupyterlab
          file: containers/jupyterlab/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            esiil/${{ steps.repo_name.outputs.repo_name }}_jupyterlab:latest
     
      - name: Image digest
        run: echo ${{ steps.docker_build_jupyterlab.outputs.digest }}
